resources:
  - ../../base

namePrefix: 
  prod-

# configMapGenerator:
#   - name: migration-job-config
#     envs:
#     - .env

patches:
- path: open-ims-config-patches.json
  target:
    group: batch
    version: v1
    kind: Job
    name: migration-job