resources:
  - ../../base
  # - postgres-credentials.yaml

namePrefix: prod-

patches:
- path: open-ims-config-patches.json
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: postgres-stateful-set

images:
- name: postgres
  newName: postgres
  newTag: '15.3'