apiVersion: skaffold/v4beta6
kind: Config

metadata:
  name: open-ims

profiles:
- name: dev
  activation:
    - command: dev
  build:
    local:
      push: false
    artifacts:
      - image: fcabrera01/open-ims-client
        context: microservices/client
        docker:
          dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "src/**/*.js"
              dest: .
            - src: "src/**/*.ts"
              dest: .
            - src: "src/**/*.tsx"
              dest: .
            - src: "src/**/*.css"
              dest: .
            - src: "vite.config.ts"
              dest: .
            - src: "src/**/*.html"
              dest: .
      - image: fcabrera01/open-ims-server
        context: microservices/server
        docker:
          dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "**/*.js"
              dest: .
            - src: "**/*.ts"
              dest: .
            - src: "tsconfig.json"
              dest: .
  manifests:
    kustomize:
      paths:
        - ./common/kustomize/overlays/dev
        - ./microservices/server/kustomize/overlays/dev
        - ./microservices/client/kustomize/overlays/dev
      