apiVersion: skaffold/v4beta6
kind: Config

metadata:
  name: open-ims

profiles:
- name: dev
  activation:
    - command: dev
  build:
    local:
      push: false
    tagPolicy:
      gitCommit: 
        prefix: "dev-"
    artifacts:
      - image: fcabrera01/open-ims-client
        context: microservices/client
        docker:
          dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "src/**/*.js"
              dest: .
            - src: "src/**/*.ts"
              dest: .
            - src: "src/**/*.tsx"
              dest: .
            - src: "src/**/*.css"
              dest: .
            - src: "vite.config.ts"
              dest: .
            - src: "src/**/*.html"
              dest: .
      - image: fcabrera01/open-ims-server
        context: microservices/server
        docker:
          dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "**/*.js"
              dest: .
            - src: "**/*.ts"
              dest: .
            - src: "tsconfig.json"
              dest: .
  manifests:
    kustomize:
      paths:
        - ./common/ingress/kustomize/overlays/dev
        - ./common/database/kustomize/overlays/dev
        - ./microservices/server/kustomize/overlays/dev
        - ./microservices/client/kustomize/overlays/dev
      
- name: staging
  build:
    tagPolicy:
      gitCommit: 
        prefix: "staging-"
    # local:
    #   push: false
    artifacts:
      - image: fcabrera01/open-ims-client
        context: microservices/client
        docker:
          dockerfile: Dockerfile
      - image: fcabrera01/open-ims-server
        context: microservices/server
        docker:
          dockerfile: Dockerfile
      # - image: fcabrera01/integration-testing
      #   context: common/testing
  manifests:
    kustomize:
      paths:
        - ./common/ingress/kustomize/overlays/staging
        - ./microservices/server/kustomize/overlays/staging
        - ./microservices/client/kustomize/overlays/staging
  verify:
    - name: alpine-wget
      container:
        name: alpine-wget
        image: alpine:3.15.4
        command: ["/bin/sh"]
        args: ["-c", "wget http://localhost/api/server/testmsg"]