apiVersion: skaffold/v4beta6
kind: Config

metadata:
  name: open-ims

profiles:
- name: dev
  activation:
    - command: dev
  manifests:
    kustomize:
      paths:
        - ./common/rbac/
        - ./common/ingress/overlays/dev
        - ./common/pgadmin/overlays/dev
        - ./common/database/kustomize/overlays/dev
        - ./microservices/server/kustomize/overlays/dev
        - ./microservices/client/kustomize/overlays/dev
        - ./common/utils/migration-job/kustomize/overlays/dev
  build:
    local:
      push: false
    # tagPolicy:
    #   gitCommit: 
    #     prefix: "dev-"
    artifacts:
      - image: fcabrera01/open-ims-client-dev
        context: microservices/client
        docker:
          dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "src/**/*.js"
              dest: .
            - src: "src/**/*.ts"
              dest: .
            - src: "src/**/*.tsx"
              dest: .
            - src: "src/**/*.css"
              dest: .
            - src: "vite.config.ts"
              dest: .
            - src: "src/**/*.html"
              dest: .
      - image: fcabrera01/open-ims-server-dev
        context: microservices/server
        docker:
          dockerfile: Dockerfile.dev
        sync:
          manual:
            - src: "src/**/*.js"
              dest: .
            - src: "src/**/*.ts"
              dest: .
            - src: "tsconfig.json"
              dest: .
            - src: "index.ts"
              dest: .
      - image: fcabrera01/ccg-migration-job
        context: common/utils/migration-job
        docker:
          dockerfile: Dockerfile
        # sync:
        #   manual:
        #     - src: "index.js"
        #       dest: .
        #     - src: "database.json"
        #       dest: .
        #     - src: "migrations/**/*.js"
        #       dest: .
        #     - src: "migrations/**/*.sql"
        #       dest: .
      
- name: prod-local
  manifests:
    kustomize:
      paths:
        - ./common/rbac/
        - ./common/ingress/overlays/prod
        - ./common/database/kustomize/overlays/prod
        - ./microservices/server/kustomize/overlays/prod
        - ./microservices/client/kustomize/overlays/prod
        - ./common/utils/migration-job/kustomize/overlays/prod
        # - ./common/pgadmin/overlays/dev
  build:
    local:
      push: false
      # push: true
    tagPolicy:
      # sha256: {}
      gitCommit: 
        prefix: "prod-"
    artifacts:
      - image: fcabrera01/ccg-client
        context: microservices/client
        docker:
          dockerfile: Dockerfile.staging
          cacheFrom:
          - "fcabrera01/ccg-client:prod-latest"
      - image: fcabrera01/ccg-server
        context: microservices/server
        docker:
          dockerfile: Dockerfile
          cacheFrom:
          - "fcabrera01/ccg-server:prod-latest"
      - image: fcabrera01/ccg-migration-job
        context: common/utils/migration-job
        docker:
          dockerfile: Dockerfile
          cacheFrom:
          - "fcabrera01/ccg-migration-job:prod-latest"
  deploy:
    kubectl: {}

- name: prod-do
  manifests:
    kustomize:
      paths:
        - ./common/rbac/
        - ./common/ingress/overlays/prod
        - ./common/database/kustomize/overlays/prod
        - ./microservices/server/kustomize/overlays/prod
        - ./microservices/client/kustomize/overlays/prod
        - ./common/utils/migration-job/kustomize/overlays/prod
  build:
    local:
      push: true
      useBuildkit: true
    tagPolicy:
      gitCommit: 
        prefix: "prod-"
    artifacts:
      - image: fcabrera01/ccg-client
        context: microservices/client
        # docker:
        #   dockerfile: Dockerfile
        #   cacheFrom:
        #   - "fcabrera01/ccg-client:prod-latest"
        #   - "type=registry,ref=fcabrera01/ccg-client:prod-builder
        custom:
          buildCommand: |
            echo
            echo "Building CCG client image '${IMAGE}' from context '${BUILD_CONTEXT}'"
            echo "Image is expected to exist remotely: ${PUSH_IMAGE}"
            echo
            docker buildx build \
              --file "${BUILD_CONTEXT}/Dockerfile" \
              --tag "${IMAGE}" \
              --cache-to "type=registry,ref=fcabrera01/ccg-client:prod-latest,mode=max" \
              --cache-from "type=registry,ref=fcabrera01/ccg-client:prod-builder" \
              --cache-from "type=registry,ref=fcabrera01/ccg-client:prod-latest" \
              --push \
              "${BUILD_CONTEXT}"

      - image: fcabrera01/ccg-server
        context: microservices/server
        docker:
          dockerfile: Dockerfile
          cacheFrom:
          - "fcabrera01/ccg-server:prod-latest"
          # - "type=registry,ref=fcabrera01/ccg-server:prod-builder"
      - image: fcabrera01/ccg-migration-job
        context: common/utils/migration-job
        docker:
          dockerfile: Dockerfile
          cacheFrom:
          - "fcabrera01/ccg-migration-job:prod-latest"
  deploy:
    kubectl: {}
  # verify:
  #   - name: alpine-wget
  #     container:
  #       name: alpine-wget
  #       image: alpine:3.15.4
  #       command: ["/bin/sh"]
  #       args: ["-c", "wget http://localhost/api/server/testmsg"]