resources:
  - ../../base

namePrefix: 
  dev-

configMapGenerator:
  - name: client-config
    envs:
      - .env

images:
- name: fcabrera01/open-ims-client
  newName: fcabrera01/open-ims-client-dev