apiVersion: 1

datasources:
  - name: Postgres
    uid: psql_dev_1
    type: postgres
    url: dev-postgres-stateful-set-0.dev-postgres-headless-service:5432
    user: dev
    secureJsonData:
      password: 'admin'
    jsonData:
      database: open-ims-dev
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+ 
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1620 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
      
  - name: Prometheus
    type: prometheus
    uid: ims-prom
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prom-cluster-ip-service.monitoring:9090/prometheus
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.53.0
      # cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      # exemplarTraceIdDestinations:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        # - datasourceUid: my_jaeger_uid
          # name: traceID

        # Field with external link.
        # - name: traceID
          # url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'

  - name: Loki
    type: loki
    uid: ims-loki
    access: proxy
    url: http://loki.monitoring:3100
    jsonData:
      timeout: 60
      maxLines: 1000