resources:
  - ../../base

namePrefix: 
  dev-

configMapGenerator:
  - name: server-config
    env: config.properties

images:
- name: fcabrera01/open-ims-server
  newName: fcabrera01/open-ims-server-dev