resources:
  - ../../base

namePrefix: 
  dev-

# configMapGenerator:
#   - name: server-config
#     envs:
#     - .env
  
# secretGenerator:
# - name: server-secrets
#   envs:
#   - .server.secrets.env

images:
- name: fcabrera01/open-ims-server
  newName: fcabrera01/open-ims-server-dev

patches:
- path: open-ims-config-patches.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: server-deployment
- path: migration-job-patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: server-deployment