resources:
  - ../../base

namePrefix: 
  prod-

# configMapGenerator:
#   - name: server-config
#     envs:
#     - .env

images:
- name: fcabrera01/open-ims-server
  newName: fcabrera01/ccg-server

patches:
- path: open-ims-config-patches.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: server-deployment
- path: migration-job-patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: server-deployment