{
 "title": "Kubernetes Monitoring Dashboard (kubelet Cadvisor, node-exporter)",
 "description": "Kubernetes Pod Resource Overview. node-exporter and kubelet-cadvisor required.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kube_node_info, node)"
   },
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$Node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{kubernetes_io_hostname=~\"^$Node$\",container!=\"\"}) by (kubernetes_io_hostname) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname) * 100",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Node CPU usage (1m avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=~\".*dev.*\",instance=~\"$host\"} - node_filesystem_avail_bytes{device=~\".*dev.*\",instance=~\"$host\"}) / (node_filesystem_size_bytes{device=~\".*dev.*\",instance=~\"$host\"}) * 100",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"^$Node$\",container!=\"\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\",instance=~\"$host\"} - node_filesystem_avail_bytes{device=~\"/dev/.*\",instance=~\"$host\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.*\",instance=~\"$host\"}",
     "legendFormat": "{{instance}}{{device}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname,namespace,pod)",
     "legendFormat": "{{ kubernetes_io_hostname}} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container!=\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname,namespace, container)",
     "legendFormat": "{{ kubernetes_io_hostname }} | {{ container}}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname,namespace,pod)",
     "legendFormat": "{{kubernetes_io_hostname}} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",namespace=~\"$namespace\",container=~\".+\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname,namespace, container)",
     "legendFormat": "{{ kubernetes_io_hostname}} | {{ container }}"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, namespace, pod)",
     "legendFormat": "-> pod {{kubernetes_io_hostname}} {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"$namespace\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, namespace,pod)",
     "legendFormat": "<- pod {{kubernetes_io_hostname}} {{ pod }}"
    }
   ]
  }
 ]
}