apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 16Gi
  accessModes:
    - ReadWriteOnce
  # storageClassName: defaults to local or do-block-storage