apiVersion: v1
kind: Service
metadata:
  # name: dev-postgres-stateful-set
  name: postgres-headless-service
  labels:
    component: database
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: postgres
      port: 5432
      targetPort: 5432
  selector:
    component: database
