apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stateful-set
spec:
  selector:
    matchLabels:
      component: database # has to match .spec.template.metadata.labels
  serviceName: postgres-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        component: database
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres:latest
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
          subPath: postgres
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-credentials
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-credentials
                key: POSTGRES_USER