apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      initContainers:
      - name: "job-wait-initcontainer"
        imagePullPolicy: IfNotPresent
        image: "groundnuty/k8s-wait-for:v2.0"
        # command: ["/usr/bin/timeout", "3", "wait_for.sh"]
        args: 
        - "job-wr"
        - "migration-job"
      containers:
      - name: server
        image: fcabrera01/open-ims-server
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1000m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: open-ims-config-map
          - secretRef:
              name: open-ims-secrets
        env:
          - name: PGPASSWORD
            value: "$(POSTGRES_PASSWORD)"
          - name: PGUSER
            value: "$(POSTGRES_USER)"
          - name: PGDATABASE
            value: "$(POSTGRES_DB)"