apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      initContainers:
      - name: "job-wait-initcontainer"
        imagePullPolicy: Always
        image: "groundnuty/k8s-wait-for:v2.0"
        # imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
        - "job-wr"
        - "migration-job"
      containers:
      - name: server
        image: fcabrera01/open-ims-server
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1000m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: server-config
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_USER
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: JWT_SECRET_KEY