apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: client
        image: fcabrera01/open-ims-client
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: open-ims-client-map
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"