apiVersion: v1
kind: Service
metadata:
  name: grafana-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - port: 3002
      protocol: TCP
      targetPort: http-grafana
  sessionAffinity: None