resources:
  - ../../base
  # - postgres-credentials.yaml

namePrefix: dev-

patches:
- path: open-ims-config-patches.json
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: postgres-stateful-set
