#! For this secret to generate correctly you need to create a ".env" file in this secrets/ directory
#! containing the same names as the one outline in the example.env file.
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  .env: {{ .Files.Get "./secrets.env" | b64enc | quote }}
