name: Main branch acceptance check
run-name: ${{ github.actor }}'s main branch PR - Skaffold Build Test

# env:
#   SERVER: production

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches: 
      - main

jobs:
  main_branch_acceptance_check:
    runs-on: ubuntu-latest
    steps:

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version

      - name: Cache skaffold image builds & config
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Pull images from DockerHub
      #   run: |   
      #     docker image pull fcabrera01/ccg-server:prod-latest
      #     docker image pull fcabrera01/ccg-client:prod-latest
          # docker image pull fcabrera01/ccg-migration-job:prod-latest
      # - name: Pull images used in --cache-from
      #   run: |
      #     echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      #     echo "Sha: ${{ env.sha_short }}

      - name: Checkout (pull) main branch onto Digital Ocean K8s Cluster
        uses: actions/checkout@v4

      - name: Build images and push them to DockerHub with the 'prod-latest' tag
        run: |
          skaffold build -p prod-do --tag='prod-latest'