name: Deploy to digital ocean
run-name: ${{ github.actor }}'s merge - Deployment to Digital Ocean

# env:
#   SERVER: production

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    # main_branch_deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version

      - name: Cache skaffold image builds & config
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout on Digital Ocean K8s Cluster
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout repository with production tags
        uses: actions/checkout@v4
        with:
          repository: ferncabrera/ccg-prod-tags
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          ref: 'master'
          path: ccg-prod-tags
          # need some flags to cherry pick commit with the correct SHA

      # - name: Build and Push to DockerHub
      #   run: |
      #     skaffold build -p prod-do --file-output='production-tags.json'

      #! Noting this here for later, we can handle errors during GA execution with the following 3 lines!
      # - name: My backup step
      #   if: ${{ failure() }}
      #   uses: actions/heroku@1.0.0

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ccg-ims

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          echo github.ref ${{github.ref}}
          echo github.ref ${{github.sha}}
      # echo ${{github.head_ref}}
      # echo ${{github.head_ref}}
      # echo ${{github.head_ref}}
      #     cd ${{github.workspace}}/main
      #     skaffold deploy -p prod-do --build-artifacts='${{github.workspace}}/ccg-prod-tags/production-deployment-tags.json'

      #? We should look into verifying the deployments after, this way we can also roll-back on deployments perhaps...
      # - name: Verify deployment
      #   run: kubectl rollout status deployment/appname -n appname
      # Need to install doctl 


    # skaffold build -p prod --file-output='production-tags.json'
    # skaffold deploy -p prod --build-artifacts='production-tags.json' --tail
# skaffold verify -p staging
# skaffold delete -p staging 
