name: Main branch image building and tagging
run-name: ${{ github.actor }}'s main branch PR - Push images and update prod deployment tags 

# env:
#   SERVER: production

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches: 
      - main

jobs:
  build_images_and_update_tags_for_main:
    runs-on: ubuntu-latest
    steps:

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version

      - name: Cache skaffold image builds & config
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout prod branch on Digital Ocean K8s Cluster
        uses: actions/checkout@v4

      - name: Checkout repository with production tags
        uses: actions/checkout@v4
        with:
          repository: ferncabrera/ccg-prod-tags
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: master
        # with:
        #   path: ${{ vars.PROD_BRANCH }}

      - name: Build images and push them (+metadata) to DockerHub with the correct tags
        run: |
          skaffold build --cache-artifacts=false -p prod-do --file-output='${{github.workspace}}/../../ccg-prod-tags/production-deployment-tags.json'