name: Build and Test

# env:
#   SERVER: production

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches: 
      - main

jobs:
  main_branch_acceptance_check:
    runs-on: ubuntu-latest
    # environment: TEST

    steps:
      - name: Build and push images 
        uses: actions/checkout@v3
        # docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        run: |-
          docker build -t fcabrera01acceptance_check_client -f ./microservices/client/Dockerfile ./microservices/client
          docker container run -it --name acceptance_check_client -p 5000:5000 fcabrera01/acceptance_check_client

        #TODO