name: Deploy to digital ocean
run-name: ${{ github.actor }}'s merge - Deployment to Digital Ocean

# env:
#   SERVER: production

on:
  push:
    branches:
      - main

jobs:
  main_branch_deployment:
    runs-on: ubuntu-latest
    steps:
      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      # Install Skaffold
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      # Cache skaffold image builds & config
      - name: Cache skaffold image builds & config
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      # Login to Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Checkout repository
      - uses: actions/checkout@v3
      - name: Build and Push to DockerHub
        run: |
          skaffold build -p prod --file-output='production-tags.json'
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-ccg-ims
      - name: Deploy to DigitalOcean Kubernetes
        run: skaffold deploy -p prod --build-artifacts='production-tags.json'
      # - name: Verify deployment
      #   run: kubectl rollout status deployment/appname -n appname
      # Need to install doctl 


    # skaffold build -p prod --file-output='production-tags.json'
    # skaffold deploy -p prod --build-artifacts='production-tags.json' --tail
# skaffold verify -p staging
# skaffold delete -p staging 
