name: Deployment preparation
run-name: Preparing to merge ${{github.event.pull_request.head.ref}} into ${{github.event.pull_request.base.ref}} - ${{github.triggering_actor}}'s run

# env:
#   SERVER: production

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    types: [opened, reopened, synchronize]
    branches: 
      - main

jobs:
  build_images_and_update_tags_for_main:
    runs-on: ubuntu-latest
    steps:

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version

      - name: Cache skaffold image builds & config
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout prod branch on Digital Ocean K8s Cluster
        uses: actions/checkout@v4
        with:
          path: main

      # - name: Checkout repository with production tags
      - uses: actions/checkout@v4
        with:
          repository: ferncabrera/ccg-prod-tags
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          ref: master
          path: ccg-prod-tags

        # with:
        #   path: ${{ vars.PROD_BRANCH }}

      - name: Build prod images and push them (+metadata) to DockerHub with the updated tags
        run: |
          cd ${{github.workspace}}/main
          skaffold build --cache-artifacts=false -p prod-do --tag='${{github.event.number}}-${{github.event.pull_request.head.sha}}' --file-output='${{github.workspace}}/ccg-prod-tags/production-deployment-tags.json'

      - name: Push new tags (and migrations in the future) to repository for deployment
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-directory: ccg-prod-tags/
          destination-github-username: 'ferncabrera'
          destination-repository-name: 'ccg-prod-tags'
          target-branch: master
          commit-message: "PR ${{github.repository}}#${{github.event.number}} now @ HEAD_COMMIT ${{github.repository}}@${{github.event.pull_request.head.sha}}"
